version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=you-contribute
      - MYSQL_ROOT_PASSWORD=mysql-root-password
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
    ports:
      - '3309:3306'